version: "3.8"

services:
  ikuai-aio:
    image: ghcr.io/nervebing/ikuai-aio:latest
    container_name: ikuai-aio
    restart: always
    environment:
      # 可选,跳过 ssl 证书检测,默认 false
      HTTP_INSECURE_SKIP_VERIFY: false
      # 可选,默认 30s
      HTTP_TIMEOUT: 30s
      # 可选,默认 Asia/Shanghai
      TZ: Asia/Shanghai
      # iKuai 地址,默认 http://192.168.1.1
      IKUAI_ADDR: http://192.168.1.1
      # iKuai 用户名,默认 admin
      IKUAI_USERNAME: admin
      # iKuai 密码,默认 admin
      IKUAI_PASSWORD: admin
      # 可选,启动容器即刻执行定时任务,设为 true 可跳过本次执行
      IKUAI_CRON_SKIP_START: false
      # 可选,多个任务用数字区分,周期/crontab格式|运营商名称|IP集地址,支持逗号分隔|备注,可为空,默认 [ikuai-aio]
      # 新增的数据会覆盖原同[运营商名称]数据
      IKUAI_CRON_CUSTOM_ISP_1: "8h|China|https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt|ikuai-aio"
      IKUAI_CRON_CUSTOM_ISP_2: "0 6 * * *|Telegram|https://xxx.com/a.txt,https://xxx.com/b.txt|ikuai-aio"
      # 可选,多个任务用数字区分,周期/crontab格式|线路,支持逗号分隔|域名集地址,支持逗号分隔|IP或IP段,可为空|备注,可为空,默认 [ikuai-aio]
      # 新增的数据会覆盖原[备注]数据
      IKUAI_CRON_STREAM_DOMAIN_1: "10m|wan2|https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt|192.168.1.10-192.168.1.20|ikuai-aio"
      # 可选, iKuai exporter 监听地址,默认 0.0.0.0:8000
      IKUAI_EXPORTER_LISTEN_ADDR: 0.0.0.0:8000
      # 可选,当设置为 true 时, exporter 不运行,默认 false
      IKUAI_EXPORTER_DISABLE: false
    ports:
      - "8000:8000"
